
services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
    volumes:
      - ./app:/app/
      # - ./ml/model/:/app/ml/model/